# Generated by Django 6.0.3 on 2026-04-22 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
